workflows:
  android-workflow:
    name: Android Build
    working_directory: app
    environment:
      flutter: stable
    scripts:
      - name: Create missing platform folders
        script: |
          if [ ! -d android ]; then
            flutter create --platforms=android .
          fi
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build APK (Demo Mode)
        script: flutter build apk --release --dart-define=DEMO_MODE=true
    artifacts:
      - app/build/app/outputs/flutter-apk/*.apk
